steps:
  - label: "Failure step"
    key: "first"
    command: exit -1

  - label: "Depended step"
    key: "second"
    command: echo "World!"
    depends_on: "first"

  - trigger: another-test-hello
    label: "Trigger another hello with env"
    depends_on: "second"
    allow_dependency_failure: true
    async: true
    build:
      env:
        PIPELINE_SLUG: "metrics-web-pipeline"
